name: Pull Request Add Laber
on:
  pull_request_target:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        uses: nelonoel/branch-name@v1
        env:
          BRANCH_NAME_VARIABLE: ${BRANCH_NAME}

      - name: Create Label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            echo ${BRANCH_NAME_VARIABLE}
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
