name: Pull Request Add Laber
on:
  pull_request_target:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Create Label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (github.head_ref == "feat/test_trigger") {

              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Triage']
              })

            }
