name: Pull Request Add Laber
on:
  pull_request_target:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Step that prints name of pull request's base branch
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
      - name: Create Label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
